services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - trino-net

  nessie:
    image: projectnessie/nessie:0.76.1
    ports:
      - "19120:19120"
    environment:
      - QUARKUS_HTTP_PORT=19120
    networks:
      - trino-net

  trino:
    image: trinodb/trino:471
    container_name: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/etc:/etc/trino
      - ./trino/data:/var/trino
      - ./scripts:/scripts
      - ./data/duckdb:/data/duckdb
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
    depends_on:
      - minio
      - nessie
    networks:
      - trino-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info/state"]
      interval: 10s
      timeout: 5s
      retries: 5

  trino-ai-only:
    image: trinodb/trino:471
    container_name: trino-ai-only
    ports:
      - "8081:8080"
    volumes: 
      - ./trino-ai-only/etc:/etc/trino
      - ./trino-ai-only/data:/var/trino/data
      - ./scripts:/scripts
    networks:
      - trino-net
    depends_on:
      trino-ai:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/info/state"]
      interval: 10s
      timeout: 5s
      retries: 5

  trino-ai:
    build: 
      context: ./trino-ai
      dockerfile: Dockerfile
    container_name: trino-ai
    ports:
      - "5001:5001"
    environment:
      - TRINO_HOST=trino
      - TRINO_PORT=8080
      - TRINO_USER=admin
      - TRINO_PASSWORD=admin
      - TRINO_CATALOG=iceberg
      - TRINO_SCHEMA=iceberg
      - OLLAMA_MODEL=llama3.2
      - OLLAMA_HOST=http://ollama:11434
      - AI_AGENT_HOST=http://trino-ai:5001
      - PYTHONUNBUFFERED=1
      - USE_GPU=auto
    volumes:
      - ./data:/app/data
      - ./.chromadb:/app/.chromadb
      - ./logs:/app/logs
    depends_on:
      trino:
        condition: service_healthy
      ollama:
        condition: service_healthy
    networks:
      - trino-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - trino-net
    environment:
      - OLLAMA_ENABLE_GPU=auto
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: ["/bin/sh"]
    command: ["-c", "ollama serve & sleep 10 && echo 'Pulling llama3.2 model...' && ollama pull llama3.2 && echo 'Model ready' && tail -f /dev/null"]

  data-loader:
    build: 
      context: ./data-loader
      dockerfile: Dockerfile
    container_name: data-loader
    env_file:
      - ./data-loader/.env
    environment:
      - TRINO_HOST=trino
      - TRINO_PORT=8080
      - TRINO_USER=admin
      - TRINO_CATALOG=iceberg
      - TRINO_SCHEMA=iceberg
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - PYTHONUNBUFFERED=1
      - DATASET_ID=${DATASET_ID:-vx8i-nprf}
    command: >
      bash -c "
        echo 'Loading NYC Popular Baby Names dataset...' &&
        python nyc_data_manager.py load-dataset --dataset-id kxp8-n2sj &&
        echo 'Loading NYC Film Permits dataset...' &&
        python nyc_data_manager.py load-dataset --dataset-id tg4x-b46p &&
        echo 'Loading NYC 2015 Street Tree Census dataset...' &&
        python nyc_data_manager.py load-dataset --dataset-id uvpi-gqnh &&
        echo 'Initializing DuckDB database...' &&
        python nyc_data_manager.py init-duckdb --db-path /data/duckdb/nyc_data.duckdb &&
        echo 'All datasets loaded successfully!'
      "
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data
      - ./logs:/app/logs
      - ./data/duckdb:/data/duckdb
    depends_on:
      trino:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - trino-net

networks:
  trino-net:
    driver: bridge

volumes:
  minio_data:
  ollama_data: